// <auto-generated />
namespace DataLayerForFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Fixing4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixing4));
        
        string IMigrationMetadata.Id
        {
            get { return "201312161339269_Fixing4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
