//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public Keyword()
        {
            this.ContactMethods = new HashSet<ContactMethod>();
            this.Contacts = new HashSet<Contact>();
            this.Keywords1 = new HashSet<Keyword>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int KeywordsId { get; set; }
        public Nullable<int> Parent_Id { get; set; }
    
        public virtual ICollection<ContactMethod> ContactMethods { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Keyword> Keywords1 { get; set; }
        public virtual Keyword Keyword1 { get; set; }
    }
}
