//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final2.Bubble {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Bubble.IContactsSoap")]
    public interface IContactsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/DoWork", ReplyAction="http://tempuri.org/IContactsSoap/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/DoWork", ReplyAction="http://tempuri.org/IContactsSoap/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/GetPeople", ReplyAction="http://tempuri.org/IContactsSoap/GetPeopleResponse")]
        DataLayerForFinal.Person[] GetPeople();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/GetPeople", ReplyAction="http://tempuri.org/IContactsSoap/GetPeopleResponse")]
        System.Threading.Tasks.Task<DataLayerForFinal.Person[]> GetPeopleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/GetEmails", ReplyAction="http://tempuri.org/IContactsSoap/GetEmailsResponse")]
        DataLayerForFinal.Email[] GetEmails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/GetEmails", ReplyAction="http://tempuri.org/IContactsSoap/GetEmailsResponse")]
        System.Threading.Tasks.Task<DataLayerForFinal.Email[]> GetEmailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/GetPhones", ReplyAction="http://tempuri.org/IContactsSoap/GetPhonesResponse")]
        DataLayerForFinal.Phone[] GetPhones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/GetPhones", ReplyAction="http://tempuri.org/IContactsSoap/GetPhonesResponse")]
        System.Threading.Tasks.Task<DataLayerForFinal.Phone[]> GetPhonesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/GetAddresses", ReplyAction="http://tempuri.org/IContactsSoap/GetAddressesResponse")]
        DataLayerForFinal.Address[] GetAddresses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/GetAddresses", ReplyAction="http://tempuri.org/IContactsSoap/GetAddressesResponse")]
        System.Threading.Tasks.Task<DataLayerForFinal.Address[]> GetAddressesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/AddPerson", ReplyAction="http://tempuri.org/IContactsSoap/AddPersonResponse")]
        void AddPerson(DataLayerForFinal.Person dude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/AddPerson", ReplyAction="http://tempuri.org/IContactsSoap/AddPersonResponse")]
        System.Threading.Tasks.Task AddPersonAsync(DataLayerForFinal.Person dude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/AddEmail", ReplyAction="http://tempuri.org/IContactsSoap/AddEmailResponse")]
        void AddEmail(DataLayerForFinal.Email em);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/AddEmail", ReplyAction="http://tempuri.org/IContactsSoap/AddEmailResponse")]
        System.Threading.Tasks.Task AddEmailAsync(DataLayerForFinal.Email em);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/AddAddress", ReplyAction="http://tempuri.org/IContactsSoap/AddAddressResponse")]
        void AddAddress(DataLayerForFinal.Address ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/AddAddress", ReplyAction="http://tempuri.org/IContactsSoap/AddAddressResponse")]
        System.Threading.Tasks.Task AddAddressAsync(DataLayerForFinal.Address ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/AddPhone", ReplyAction="http://tempuri.org/IContactsSoap/AddPhoneResponse")]
        void AddPhone(DataLayerForFinal.Phone pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/AddPhone", ReplyAction="http://tempuri.org/IContactsSoap/AddPhoneResponse")]
        System.Threading.Tasks.Task AddPhoneAsync(DataLayerForFinal.Phone pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/Save", ReplyAction="http://tempuri.org/IContactsSoap/SaveResponse")]
        void Save();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/Save", ReplyAction="http://tempuri.org/IContactsSoap/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/RemovePerson", ReplyAction="http://tempuri.org/IContactsSoap/RemovePersonResponse")]
        void RemovePerson(DataLayerForFinal.Person dude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/RemovePerson", ReplyAction="http://tempuri.org/IContactsSoap/RemovePersonResponse")]
        System.Threading.Tasks.Task RemovePersonAsync(DataLayerForFinal.Person dude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/RemoveEmail", ReplyAction="http://tempuri.org/IContactsSoap/RemoveEmailResponse")]
        void RemoveEmail(DataLayerForFinal.Email em);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/RemoveEmail", ReplyAction="http://tempuri.org/IContactsSoap/RemoveEmailResponse")]
        System.Threading.Tasks.Task RemoveEmailAsync(DataLayerForFinal.Email em);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/RemoveAddress", ReplyAction="http://tempuri.org/IContactsSoap/RemoveAddressResponse")]
        void RemoveAddress(DataLayerForFinal.Address ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/RemoveAddress", ReplyAction="http://tempuri.org/IContactsSoap/RemoveAddressResponse")]
        System.Threading.Tasks.Task RemoveAddressAsync(DataLayerForFinal.Address ad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/RemovePhone", ReplyAction="http://tempuri.org/IContactsSoap/RemovePhoneResponse")]
        void RemovePhone(DataLayerForFinal.Phone pn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactsSoap/RemovePhone", ReplyAction="http://tempuri.org/IContactsSoap/RemovePhoneResponse")]
        System.Threading.Tasks.Task RemovePhoneAsync(DataLayerForFinal.Phone pn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactsSoapChannel : Final2.Bubble.IContactsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactsSoapClient : System.ServiceModel.ClientBase<Final2.Bubble.IContactsSoap>, Final2.Bubble.IContactsSoap {
        
        public ContactsSoapClient() {
        }
        
        public ContactsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public DataLayerForFinal.Person[] GetPeople() {
            return base.Channel.GetPeople();
        }
        
        public System.Threading.Tasks.Task<DataLayerForFinal.Person[]> GetPeopleAsync() {
            return base.Channel.GetPeopleAsync();
        }
        
        public DataLayerForFinal.Email[] GetEmails() {
            return base.Channel.GetEmails();
        }
        
        public System.Threading.Tasks.Task<DataLayerForFinal.Email[]> GetEmailsAsync() {
            return base.Channel.GetEmailsAsync();
        }
        
        public DataLayerForFinal.Phone[] GetPhones() {
            return base.Channel.GetPhones();
        }
        
        public System.Threading.Tasks.Task<DataLayerForFinal.Phone[]> GetPhonesAsync() {
            return base.Channel.GetPhonesAsync();
        }
        
        public DataLayerForFinal.Address[] GetAddresses() {
            return base.Channel.GetAddresses();
        }
        
        public System.Threading.Tasks.Task<DataLayerForFinal.Address[]> GetAddressesAsync() {
            return base.Channel.GetAddressesAsync();
        }
        
        public void AddPerson(DataLayerForFinal.Person dude) {
            base.Channel.AddPerson(dude);
        }
        
        public System.Threading.Tasks.Task AddPersonAsync(DataLayerForFinal.Person dude) {
            return base.Channel.AddPersonAsync(dude);
        }
        
        public void AddEmail(DataLayerForFinal.Email em) {
            base.Channel.AddEmail(em);
        }
        
        public System.Threading.Tasks.Task AddEmailAsync(DataLayerForFinal.Email em) {
            return base.Channel.AddEmailAsync(em);
        }
        
        public void AddAddress(DataLayerForFinal.Address ad) {
            base.Channel.AddAddress(ad);
        }
        
        public System.Threading.Tasks.Task AddAddressAsync(DataLayerForFinal.Address ad) {
            return base.Channel.AddAddressAsync(ad);
        }
        
        public void AddPhone(DataLayerForFinal.Phone pn) {
            base.Channel.AddPhone(pn);
        }
        
        public System.Threading.Tasks.Task AddPhoneAsync(DataLayerForFinal.Phone pn) {
            return base.Channel.AddPhoneAsync(pn);
        }
        
        public void Save() {
            base.Channel.Save();
        }
        
        public System.Threading.Tasks.Task SaveAsync() {
            return base.Channel.SaveAsync();
        }
        
        public void RemovePerson(DataLayerForFinal.Person dude) {
            base.Channel.RemovePerson(dude);
        }
        
        public System.Threading.Tasks.Task RemovePersonAsync(DataLayerForFinal.Person dude) {
            return base.Channel.RemovePersonAsync(dude);
        }
        
        public void RemoveEmail(DataLayerForFinal.Email em) {
            base.Channel.RemoveEmail(em);
        }
        
        public System.Threading.Tasks.Task RemoveEmailAsync(DataLayerForFinal.Email em) {
            return base.Channel.RemoveEmailAsync(em);
        }
        
        public void RemoveAddress(DataLayerForFinal.Address ad) {
            base.Channel.RemoveAddress(ad);
        }
        
        public System.Threading.Tasks.Task RemoveAddressAsync(DataLayerForFinal.Address ad) {
            return base.Channel.RemoveAddressAsync(ad);
        }
        
        public void RemovePhone(DataLayerForFinal.Phone pn) {
            base.Channel.RemovePhone(pn);
        }
        
        public System.Threading.Tasks.Task RemovePhoneAsync(DataLayerForFinal.Phone pn) {
            return base.Channel.RemovePhoneAsync(pn);
        }
    }
}
