//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Id = 1;
            this.Phones = new HashSet<Phone>();
            this.Emails = new HashSet<Email>();
            this.Addresses = new HashSet<Address>();
            this.Restaurants = new HashSet<Restaurant>();
        }
    
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public short FavoriteHobby { get; set; }
        public short FavoriteRestaurant { get; set; }
    
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Hobby Hobby { get; set; }
        public virtual Employment Employment { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
    }
}
