//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public Phone()
        {
            this.Types = new HashSet<Type>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public short Person { get; set; }
        public short Type { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Person Person1 { get; set; }
        public virtual ICollection<Type> Types { get; set; }
        public virtual Company Company { get; set; }
    }
}
