//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public short FoodType { get; set; }
        public string CreatedOn { get; set; }
        public string ModifiedOn { get; set; }
    
        public virtual FoodType FoodType1 { get; set; }
        public virtual Person Person { get; set; }
    }
}
